# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11']
        R: [ '4.2.2' ]

    steps:
      - uses: actions/checkout@v3
      - name: Setup R ${{ matrix.R }}
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.R }}
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Python dependencies
        run: |
          Rscript -e "install.packages('ape', repos='http://cran.us.r-project.org')"
          python -m pip install --upgrade pip
          pip install .
          pip install ruff pytest scipy numpy matplotlib tensorflow keras scikit-learn dendropy pandas pypdf joblib tqdm
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
#       - name: Lint with ruff
#         run: |
#           # stop the build if there are Python syntax errors or undefined names
#           ruff --format=github --select=E9,F63,F7,F82 --target-version=py37 .
#           # default set of ruff rules with GitHub Annotations
#           ruff --format=github --target-version=py37 .
      - name: Test with pytest
        run: |
          pytest tests/
